version: '3.9'
services:
  database:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pastry_shop
      MYSQL_USER: cukorvirag
      MYSQL_PASSWORD: 20Pont
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
